### ISSUE TITLE
Notification that you've been assigned a review

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#136] opened 2019-07-24 16:33 UTC
Should there be an email? What information should be in it? Should there be notifications when you log in? Where would they go?

**Comment by lmkw** [comment] 2019-08-14 20:04
dependent on #147

**Comment by jseraf** [comment] 2019-08-14 21:03
Duplicate of #144. Un-/assign email notifications added there. 

Note: Text of outgoing email needs to be re-written. See:
https://github.com/NUARIG/competitions/tree/develop/app/views/reviewer_mailer

**Closed** 2019-10-23 20:27 UTC
