### ISSUE TITLE
Applying to a grant on behalf of another user

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#249] opened 2019-11-04 20:04 UTC
Related to #636 and #786

**Comment by jseraf** [comment] 2021-03-17 19:41
Notes from meeting w/ Laura and Matt:

CHANGES TO EXISTING TABLES/MODELS
- Grant
  - Optional to allow people to apply on behalf of someone else
- GrantPermissions
  - Admins/editors are able change applicant to another user
- Submission
  - Created_by never changes

NEW STUFF
- User
  - Email would have to exist in the system

- GrantSubmission::Submission::SubmissionUserRole table?
  - submission_id
  - user_id
  - role (enum)
    - Applicant
      - defaults to the submitter unless otherwise assigned
  - NOTE: this sets up for collaborator role later

ISSUES/CONCERNS
- Confirm w/ Keith that a user has to sign in beforehand
- If invites were a thing they might look like this:
  - SubmissionInvite
    - submission_id 
    - inviter_id
    - user_id (if/when they have an account)
    - email
    - first name 
    - last name
    - confirmed_at?

**Comment by lmkw** [comment] 2021-03-17 21:30
@jpatel , @fanglinnw , are either of you able to weigh in on the ability to invite / add users to a system so that they can then be assigned a role on a submission? We are running into this problem again and again in Competitions--when assigning reviewers, when submitting an application on behalf of someone, etc. If the person doesn't exist in the user table, we come to an impasse.

**Comment by fanglinnw** [comment] 2021-03-17 21:55
@lmkw , it seems the existing feature to invite grant reviewers by email can be extended to support other roles. You can add a field in the GrantReviewer::Invitation model to indicate the type of roles such as reviewer, applicant, and the actual role will be assigned upon account creation depending on the value of this field. I might be missing some details but If this extension works, it might not be necessary to add a new SubmissionInvite model. 
As to the user model, I'm not sure why the email has to be in the system. @jseraf and @mattbaumann1 , let me know if you want to schedule a call to discuss this or we can chat in Teams.

**Comment by jseraf** [comment] 2021-03-17 21:59
@fanglinnw email is the unique id for users in competitions due to devise saml/registerable authentication

**Comment by jpatel** [comment] 2021-03-17 22:01
Plus, I would also look into solution, where admin can add someone in the system itself.
If its not NU user, admin can manually them with into registration table with manually entering information needed for that.
If its NU users, directory service can be used to lookup users. There are few already here, which can be used to pull validated users.

- https://apiserviceregistry.northwestern.edu/apis/identity-management-apis/IdentityManagement-DirectorySearchBasic.html
- https://apiserviceregistry.northwestern.edu/apis/identity-management-apis/IdentityManagement-DirectorySearchExpanded.html
- https://apiserviceregistry.northwestern.edu/apis/identity-management-apis/IdentityManagement-DirectorySearchPublic.html

Those users, added manually can be marked as non-verified initially, if competitions requires them to be verified upon login.

**Comment by jpatel** [comment] 2021-03-17 22:06
@jseraf and @mattbaumann1  We have user creation functionality in ST with LDAP and Lurie ST with SAML authentication  and LDAP lookup both at a same time. Please let me know if decided to pick this route.

**Comment by jseraf** [comment] 2021-03-17 22:09
@jpatel because this is an open source project, we are avoiding any ldap integration

**Comment by jpatel** [comment] 2021-03-17 22:59
@jseraf: Ldap implementation is not specific to NU.  LDAP is general authentication and lookup system available for most of organization. 
we are using general  open source ldap https://www.rubydoc.info/gems/ruby-net-ldap/Net/LDAP library to lookup. Specific LDAP informaton is only set into ldap.yml configurations. 

You can add few configurations like use_ldap_for_exteranal_user_search or something, so this lookup functionality is only available to application which has this value set.

**Comment by jpatel** [comment] 2021-03-18 00:06
if system does not require many manual user creation, you may not need lookup at all. Lookup is helpful when you need to create users often/or knows email but no other user information, lookup acts as autocomplete and pulls information for you when creating user.

You can have feature, when applying for grant for someone else, current user can
1. search user first by email i system
2. If user found, select user
3. if user not found, present UI to create user manually with all information required for User creation.  If system capture domain (northwestern.edu, lurie.org) at configuration, 
 3.1 system can tied User type to Saml or Registered user from email and domain info read from configuration, in back end while creating user automatically
 3.2 system can ask current user to select type as a part of user creation form.

In this scenario you do not need lookup.

**Comment by lmkw** [comment] 2021-03-22 18:25
Reuse reviewer invitation code, create a kind of pending/invited user status for anyone invited (as a reviewer or as an applicant) which requires them to log in before they can get the next status (applicant / reviewer / whathaveyou)

**Comment by lmkw** [comment] 2021-03-22 19:10
Decision: 
Allow submitters to invite a person to be an applicant, the way grant admins invite people to be reviewers.
This property of whether an application can have a different submitter than applicant can be specified by a grant (i.e. needs to be a checkbox or question on either Overview or Submission Form)
By default pull submitter name into applicant field but it can be overwritten by the submitter. This is where they invite 1 or more applicants
Submitter can save as draft but cannot submit until the applicant has logged in
Applicants, once they log in, can collaborate on the submission

**Comment by mattbaumann1** [comment] 2021-05-18 15:31
In this UI ticket, pay special attention to spec/system/grant_submissions/grant_submission_submission_spec.rb and how the submitter specs will change. 

```
      context 'submitter' do
        before(:each) do
          other_submission.save
          login_user submitter
          visit grant_submissions_path(grant)

        context 'submitted submission' do
          scenario 'includes link to own submission' do
          scenario 'does not have admin links' do
          scenario 'does not include other submitter submission' do
          scenario 'does not include score columns' do

        context 'draft submission' do
          scenario 'includes edit links' do
          scenario 'does not have admin links' do
```

**Comment by mattbaumann1** [comment] 2021-06-15 14:35
Update:
- [ ] Add applicants to grant/submissions index
- [ ] Add applicants to grant/submission edit
- [ ] Add ability to remove applicants
- [ ] Add ability to create applicants
- [ ] Fix broken search functionality
- [ ] Fix broken sort functionality
- [ ] Adjust policies accordingly
- [ ] Add applicants to excel export of grant/submissions
- [ ] Add applicants to grant/reviews index
- [ ] Add applicants to grant/reviews export
- [ ] Add applicants to profile/review index
- [ ] Add applicants to profile/review export 
- [ ] Add applicants to panels content

**Comment by mattbaumann1** [comment] 2021-06-15 14:40
Invitations will be handled in #828.

We will also decide whether to create an LDAP user in that ticket.

**Comment by mattbaumann1** [comment] 2021-07-12 14:24
Still finishing up specs as of 20210712. Move to next sprint.

**Closed** 2021-07-28 18:32 UTC
Labels: Community Feedback, submissions
