### ISSUE TITLE
Unable to submit edits to review

### ISSUE THREAD

**Issue by uncanny-valley-girl** [NUARIG/competitions#176] opened 2019-09-04 19:36 UTC
When I click "submit your review" when editing a review I already submitted (/grants/pretzels/submissions/{submission}/reviews/{review}/edit), nothing happens and my changes are not there when I renavigate to the review.

**Comment by lmkw** [comment] 2019-09-11 16:08
Closing because can't reproduce issue

**Closed by lmkw** 2019-09-11 16:08 UTC
